"use client";
import { useState, useEffect, useRef } from "react";
import {
  FiBell, FiShield, FiActivity, FiBarChart2, FiZap,
  FiChevronRight, FiCheck, FiX, FiMenu, FiArrowRight,
  FiStar, FiTrendingUp, FiClock, FiSmartphone, FiUsers, FiLock
} from "react-icons/fi";
import {
  RiBrainLine, RiInstagramLine, RiYoutubeLine,
  RiWhatsappLine, RiTwitterXLine, RiFacebookBoxLine,
  RiSnapchatLine, RiTiktokLine, RiLinkedinBoxLine,
  RiNotification3Line, RiShieldCheckLine, RiLineChartLine,
  RiLeafLine, RiHeartLine, RiFireLine,
  RiLightbulbFill
} from "react-icons/ri";
import { MdOutlineSpeed, MdOutlineAnalytics } from "react-icons/md";
import { useRouter } from "next/navigation";
/* ─────────────────────────────────────────────────────────────
   ADDICTION DETECTION ENGINE  (runs entirely client-side)
   Based on behavioral scoring algorithm:
   Score = Σ(featureᵢ × weightᵢ)  →  normalised 0–100
───────────────────────────────────────────────────────────── */

// Platform metadata
const PLATFORMS = {
  instagram: { name: "Instagram",  icon: RiInstagramLine,  color: "#E1306C", bg: "rgba(225,48,108,.12)",  limit: 60  },
  youtube:   { name: "YouTube",    icon: RiYoutubeLine,    color: "#FF0000", bg: "rgba(255,0,0,.10)",     limit: 90  },
  whatsapp:  { name: "WhatsApp",   icon: RiWhatsappLine,   color: "#25D366", bg: "rgba(37,211,102,.10)",  limit: 60  },
  facebook:  { name: "Facebook",   icon: RiFacebookBoxLine,color: "#1877F2", bg: "rgba(24,119,242,.10)",  limit: 60  },
  twitter:   { name: "Twitter/X",  icon: RiTwitterXLine,   color: "#000000", bg: "rgba(0,0,0,.08)",       limit: 45  },
  tiktok:    { name: "TikTok",     icon: RiTiktokLine,     color: "#010101", bg: "rgba(1,1,1,.08)",       limit: 30  },
  snapchat:  { name: "Snapchat",   icon: RiSnapchatLine,   color: "#FFFC00", bg: "rgba(255,252,0,.15)",   limit: 30  },
  linkedin:  { name: "LinkedIn",   icon: RiLinkedinBoxLine,color: "#0A66C2", bg: "rgba(10,102,194,.10)",  limit: 30  },
};

// Feature weights for addiction score
const WEIGHTS = {
  dailyTime:      0.25,  // daily screen time vs limit
  lateNight:      0.20,  // usage after 10 PM
  frequency:      0.20,  // session open count
  scrollDepth:    0.15,  // estimated scroll depth
  interaction:    0.10,  // passive vs active usage ratio
  mood:           0.10,  // self-reported mood impact
};

// Generate realistic mock usage data for a user based on phone/username seed
function generateUserData(seed) {
  const hash = [...seed].reduce((a, c) => (a * 31 + c.charCodeAt(0)) | 0, 0);
  const rng = (min, max, offset = 0) => {
    const n = Math.abs((hash + offset) * 1664525 + 1013904223) % 1000 / 1000;
    return Math.round(min + n * (max - min));
  };

  const platforms = {};
  let totalMinutes = 0;

  Object.entries(PLATFORMS).forEach(([key, p], i) => {
    const active = rng(0, 1, i * 7) > 0.2; // 80% chance active
    if (!active) { platforms[key] = null; return; }

    const todayMins  = rng(5, p.limit * 2.5, i * 13);
    const weekMins   = rng(todayMins * 5, todayMins * 9, i * 19);
    const opens      = rng(2, 28, i * 11);
    const lateNight  = rng(0, 1, i * 17) > 0.5;
    const deepScroll = rng(0, 100, i * 23);

    totalMinutes += todayMins;
    platforms[key] = {
      todayMins, weekMins, opens, lateNight, deepScroll,
      overLimit: todayMins > p.limit,
      pct: Math.min(100, Math.round((todayMins / p.limit) * 100)),
    };
  });

  // Compute addiction score
  const activeList = Object.entries(platforms).filter(([, v]) => v);
  const avgOverLimit = activeList.reduce((s, [k, v]) =>
    s + Math.max(0, v.todayMins - PLATFORMS[k].limit) / PLATFORMS[k].limit, 0) / activeList.length;
  const lateNightRatio = activeList.filter(([, v]) => v.lateNight).length / activeList.length;
  const avgFreq = activeList.reduce((s, [, v]) => s + v.opens, 0) / activeList.length;
  const avgScroll = activeList.reduce((s, [, v]) => s + v.deepScroll, 0) / activeList.length;

  const rawScore =
    Math.min(1, avgOverLimit)   * WEIGHTS.dailyTime   * 100 +
    lateNightRatio               * WEIGHTS.lateNight   * 100 +
    Math.min(1, avgFreq / 20)    * WEIGHTS.frequency   * 100 +
    (avgScroll / 100)            * WEIGHTS.scrollDepth * 100 +
    0.5                          * WEIGHTS.interaction * 100 +
    0.4                          * WEIGHTS.mood        * 100;

  const score = Math.min(100, Math.max(8, Math.round(rawScore)));
  const level = score < 30 ? "Low" : score < 60 ? "Moderate" : "High";
  const levelColor = score < 30 ? "#10B981" : score < 60 ? "#F97316" : "#EF4444";

  // Weekly trend (7 days)
  const weekTrend = Array.from({ length: 7 }, (_, i) => ({
    day: ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"][i],
    score: Math.min(100, Math.max(5, score + rng(-15, 15, i * 31))),
    mins: Math.round(totalMinutes * (0.7 + rng(0, 60, i * 41) / 100)),
  }));

  // Alerts generated by alert engine
  const alerts = generateAlerts(platforms, score, lateNightRatio);

  // Recommendations from AI engine
  const recommendations = generateRecommendations(platforms, score, avgFreq, lateNightRatio);

  return { platforms, totalMinutes, score, level, levelColor, weekTrend, alerts, recommendations, activeList };
}

// Alert generation engine
function generateAlerts(platforms, score, lateNightRatio) {
  const alerts = [];
  Object.entries(platforms).forEach(([key, v]) => {
    if (!v) return;
    const p = PLATFORMS[key];
    if (v.overLimit) alerts.push({ type: "warning", icon: "⚠️", color: "#EF4444",
      title: `High ${p.name} Usage`, desc: `${v.todayMins}m used — ${v.todayMins - p.limit}m over your ${p.limit}m daily limit`, time: "Just now" });
    if (v.lateNight)  alerts.push({ type: "night",   icon: "🌙", color: "#F97316",
      title: `Late-night ${p.name}`, desc: `Usage detected after 10 PM — impacts sleep quality and addiction score`, time: "Last night" });
  });
  if (score > 60) alerts.unshift({ type: "critical", icon: "🚨", color: "#DC2626",
    title: "High Addiction Risk Detected", desc: `Your addiction score is ${score}/100. Immediate intervention recommended.`, time: "2 hrs ago" });
  if (lateNightRatio > 0.5) alerts.push({ type: "info", icon: "💡", color: "#0D9488",
    title: "AI Recommendation Ready", desc: "New personalised action plan generated based on your behaviour pattern", time: "Today" });
  return alerts.slice(0, 6);
}

// AI Recommendation engine
function generateRecommendations(platforms, score, avgFreq, lateNightRatio) {
  const recos = [];
  if (lateNightRatio > 0.4) recos.push({ icon: "🌙", color: "#6D2E46",
    title: "Enable Night Lock", desc: "Block social apps after 10 PM. Could reduce your score by ~12 points.", action: "Apply" });
  if (avgFreq > 15) recos.push({ icon: "📵", color: "#EF4444",
    title: "Session Frequency Alert", desc: `You open apps ${Math.round(avgFreq)}x/day avg. Set a 10-open daily cap.`, action: "Set Cap" });
  const overLimitApps = Object.entries(platforms).filter(([, v]) => v?.overLimit);
  if (overLimitApps.length > 0) recos.push({ icon: "⏰", color: "#F97316",
    title: `Limit ${PLATFORMS[overLimitApps[0][0]].name}`, desc: `Set a ${PLATFORMS[overLimitApps[0][0]].limit}m daily cap. You exceeded it by ${overLimitApps[0][1].todayMins - PLATFORMS[overLimitApps[0][0]].limit}m today.`, action: "Set Limit" });
  if (score > 40) recos.push({ icon: "🧘", color: "#0D9488",
    title: "Mindfulness Breaks", desc: "5-min break every 45 min of usage reduces daily screen time by 1.8h avg.", action: "Schedule" });
  recos.push({ icon: "📊", color: "#065A82",
    title: "Weekly Report", desc: "Download your full behavioural analysis PDF to track long-term progress.", action: "Download" });
  return recos;
}

/* ─────────────────────────────────────────────────────────────
   STYLES
───────────────────────────────────────────────────────────── */
const STYLES = `
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&family=DM+Sans:ital,wght@0,300;0,400;0,500;0,600;1,400&family=JetBrains+Mono:wght@400;600&display=swap');

:root {
  --navy:#0B1F4B; --navy2:#1A3A6B; --teal:#0D9488; --teal2:#14B8A6;
  --orange:#F97316; --red:#EF4444; --green:#10B981;
  --bg:#F8FAFC; --card:#fff; --text:#1E293B; --muted:#64748B; --border:#E2E8F0;
}
*, *::before, *::after { box-sizing:border-box; margin:0; padding:0; }
html { scroll-behavior: smooth; }
body { font-family:'DM Sans',sans-serif; background:var(--bg); color:var(--text); overflow-x:hidden; }
.syne { font-family:'Poppins',sans-serif; }
.mono { font-family:'JetBrains Mono',monospace; }

/* scrollbar */
::-webkit-scrollbar{width:5px} ::-webkit-scrollbar-thumb{background:var(--border);border-radius:3px}

/* animations */
@keyframes fadeUp { from{opacity:0;transform:translateY(24px)} to{opacity:1;transform:translateY(0)} }
@keyframes pulseDot { 0%,100%{opacity:1;transform:scale(1)} 50%{opacity:.4;transform:scale(1.5)} }
@keyframes float { 0%,100%{transform:translateY(0)} 50%{transform:translateY(-10px)} }
@keyframes shimmer { from{background-position:-200% 0} to{background-position:200% 0} }
@keyframes scoreCount { from{opacity:0;transform:scale(.5)} to{opacity:1;transform:scale(1)} }
@keyframes spin { to{transform:rotate(360deg)} }
@keyframes slideInRight { from{opacity:0;transform:translateX(40px)} to{opacity:1;transform:translateX(0)} }
@keyframes gradShift { 0%{background-position:0% 50%} 50%{background-position:100% 50%} 100%{background-position:0% 50%} }

.fade-up { animation: fadeUp .6s ease both; }
.delay-1{animation-delay:.1s}.delay-2{animation-delay:.2s}.delay-3{animation-delay:.3s}
.delay-4{animation-delay:.4s}.delay-5{animation-delay:.5s}.delay-6{animation-delay:.6s}
.float { animation: float 3s ease-in-out infinite; }

/* ── NAV ── */
.lp-nav {
  position:fixed; top:0; left:0; right:0; z-index:999;
  background:rgba(11,31,75,.96); backdrop-filter:blur(14px);
  border-bottom:1px solid rgba(13,148,136,.2);
}
.lp-brand { font-family:'Syne',sans-serif; font-weight:800; font-size:1.4rem; color:#fff; letter-spacing:-.5px; cursor:pointer; }
.lp-brand span { color:var(--teal2); }
.lp-navlink { color:rgba(255,255,255,.7); font-size:.9rem; font-weight:500; text-decoration:none; cursor:pointer; transition:color .2s; }
.lp-navlink:hover { color:#fff; }
.btn-nav { background:var(--teal); color:#fff; border:none; border-radius:8px; padding:8px 20px; font-weight:600; font-size:.88rem; cursor:pointer; transition:all .2s; }
.btn-nav:hover { background:var(--teal2); transform:translateY(-1px); }
.hamburger { display:none; background:none; border:none; cursor:pointer; color:#fff; padding:4px; }

/* ── HERO ── */
.hero {
  min-height:100vh; padding-top:80px;
  background: linear-gradient(135deg,#050E2B 0%,#0B1F4B 40%,#0D4A46 100%);
  background-size:400% 400%; animation:gradShift 12s ease infinite;
  display:flex; align-items:center; position:relative; overflow:hidden;
}
.hero::before {
  content:''; position:absolute; top:-20%; right:-5%; width:640px; height:640px;
  border-radius:50%; background:radial-gradient(circle,rgba(13,148,136,.18) 0%,transparent 70%); pointer-events:none;
}
.hero-badge {
  display:inline-flex; align-items:center; gap:8px;
  background:rgba(13,148,136,.18); border:1px solid rgba(20,184,166,.35);
  color:var(--teal2); border-radius:100px; padding:6px 16px;
  font-size:.78rem; font-weight:700; letter-spacing:.6px; margin-bottom:22px;
}
.hero-h1 { font-family:'Syne',sans-serif; font-size:clamp(2.2rem,5vw,3.8rem); font-weight:800; color:#fff; line-height:1.1; letter-spacing:-1px; }
.hero-h1 .acc { color:var(--teal2); }
.hero-sub { color:rgba(255,255,255,.7); font-size:1.05rem; line-height:1.75; max-width:480px; }
.btn-primary { background:var(--orange); color:#fff; border:none; border-radius:12px; padding:14px 32px; font-family:'Syne',sans-serif; font-weight:700; font-size:1rem; cursor:pointer; display:inline-flex; align-items:center; gap:8px; transition:all .2s; }
.btn-primary:hover { transform:translateY(-2px); box-shadow:0 12px 28px rgba(249,115,22,.4); }
.btn-outline { background:transparent; color:#fff; border:2px solid rgba(255,255,255,.28); border-radius:12px; padding:14px 28px; font-family:'Syne',sans-serif; font-weight:600; font-size:1rem; cursor:pointer; display:inline-flex; align-items:center; gap:8px; transition:all .2s; text-decoration:none; }
.btn-outline:hover { border-color:#fff; background:rgba(255,255,255,.07); color:#fff; }

/* Score Widget */
.score-widget { background:rgba(255,255,255,.06); backdrop-filter:blur(20px); border:1px solid rgba(255,255,255,.12); border-radius:22px; padding:28px; max-width:340px; width:100%; }
.score-ring-wrap { position:relative; width:150px; height:150px; margin:0 auto 16px; }
.score-ring-center { position:absolute; inset:0; display:flex; flex-direction:column; align-items:center; justify-content:center; }
.score-val { font-family:'Syne',sans-serif; font-size:2.4rem; font-weight:800; color:#fff; animation:scoreCount .8s ease; }
.sbar-row { display:flex; align-items:center; gap:10px; margin:7px 0; }
.sbar-name { font-size:.7rem; color:rgba(255,255,255,.6); width:80px; }
.sbar-track { flex:1; height:5px; background:rgba(255,255,255,.1); border-radius:3px; overflow:hidden; }
.sbar-fill { height:100%; border-radius:3px; }
.sbar-val { font-size:.7rem; color:#fff; font-weight:600; width:28px; text-align:right; }
.pulse-dot { display:inline-block; width:8px; height:8px; border-radius:50%; background:var(--green); animation:pulseDot 2s infinite; }

/* ── TRUST STRIP ── */
.trust-strip { background:var(--navy); padding:52px 0; }
.trust-num { font-family:'Syne',sans-serif; font-size:2.4rem; font-weight:800; color:var(--teal2); }
.trust-lbl { color:rgba(255,255,255,.5); font-size:.86rem; margin-top:4px; }

/* ── SECTIONS ── */
.section-eyebrow { font-size:.74rem; font-weight:700; letter-spacing:2px; text-transform:uppercase; color:var(--teal); margin-bottom:10px; }
.section-h2 { font-family:'Syne',sans-serif; font-size:clamp(1.8rem,3vw,2.5rem); font-weight:800; letter-spacing:-.5px; line-height:1.15; }
.section-sub { color:var(--muted); font-size:.98rem; line-height:1.75; max-width:520px; }

/* ── DEMO / LOOKUP SECTION ── */
.demo-section { padding:100px 0; background:#fff; }
.lookup-card { background:var(--bg); border:1px solid var(--border); border-radius:20px; padding:32px; }
.lookup-input { width:100%; padding:14px 18px; border:2px solid var(--border); border-radius:12px; font-size:1rem; font-family:'DM Sans',sans-serif; outline:none; transition:border-color .2s; background:#fff; }
.lookup-input:focus { border-color:var(--teal); }
.btn-lookup { background:var(--navy); color:#fff; border:none; border-radius:12px; padding:14px 28px; font-weight:700; font-family:'Syne',sans-serif; cursor:pointer; transition:all .2s; white-space:nowrap; }
.btn-lookup:hover { background:var(--teal); }
.btn-lookup.loading { opacity:.7; cursor:wait; }

/* Result cards */
.result-card { background:#fff; border:1px solid var(--border); border-radius:16px; overflow:hidden; animation:fadeUp .4s ease; }
.rc-header { background:var(--navy); padding:16px 20px; display:flex; align-items:center; justify-content:space-between; }
.rc-score { font-family:'Syne',sans-serif; font-size:1.8rem; font-weight:800; }
.platform-row { display:flex; align-items:center; padding:12px 16px; border-bottom:1px solid rgba(0,0,0,.04); }
.platform-row:last-child { border-bottom:none; }
.p-icon { width:34px; height:34px; border-radius:9px; display:flex; align-items:center; justify-content:center; font-size:1rem; margin-right:12px; flex-shrink:0; }
.p-bar { height:6px; background:var(--bg); border-radius:3px; overflow:hidden; flex:1; margin:0 10px; }
.p-bar-fill { height:100%; border-radius:3px; transition:width 1s cubic-bezier(.4,0,.2,1); }
.p-time { font-size:.78rem; font-weight:700; width:40px; text-align:right; font-family:'JetBrains Mono',monospace; }
.over-limit { color:var(--red); }

/* Alert list */
.alert-item { display:flex; align-items:flex-start; gap:12px; padding:14px 0; border-bottom:1px solid var(--bg); }
.alert-item:last-child { border-bottom:none; }
.alert-icon-box { width:36px; height:36px; border-radius:9px; display:flex; align-items:center; justify-content:center; font-size:1rem; flex-shrink:0; }

/* ── FEATURES ── */
.features-section { padding:100px 0; background:var(--bg); }
.feat-card { background:#fff; border:1px solid var(--border); border-radius:20px; padding:30px; height:100%; transition:all .25s; position:relative; overflow:hidden; }
.feat-card::after { content:''; position:absolute; top:0; left:0; right:0; height:3px; background:linear-gradient(90deg,var(--teal),var(--orange)); transform:scaleX(0); transform-origin:left; transition:transform .3s; }
.feat-card:hover::after { transform:scaleX(1); }
.feat-card:hover { transform:translateY(-5px); box-shadow:0 18px 44px rgba(0,0,0,.1); }
.feat-icon { width:52px; height:52px; border-radius:14px; display:flex; align-items:center; justify-content:center; margin-bottom:18px; }

/* ── HOW IT WORKS ── */
.how-section { padding:100px 0; background:#fff; }
.step-num { width:56px; height:56px; border-radius:50%; background:var(--navy); color:#fff; font-family:'Syne',sans-serif; font-weight:800; font-size:1.15rem; display:flex; align-items:center; justify-content:center; margin:0 auto 16px; }

/* ── PRICING ── */
.pricing-section { padding:100px 0; background:var(--bg); }
.price-card { background:#fff; border:1px solid var(--border); border-radius:22px; padding:36px; height:100%; transition:all .25s; position:relative; }
.price-card.featured { background:var(--navy); border-color:var(--teal); }
.price-card.featured h3, .price-card.featured .price-amt { color:#fff; }
.price-card.featured .pf-item { color:rgba(255,255,255,.7); }
.price-badge { position:absolute; top:-13px; left:50%; transform:translateX(-50%); background:var(--orange); color:#fff; border-radius:100px; padding:4px 16px; font-size:.72rem; font-weight:700; white-space:nowrap; }
.price-amt { font-family:'Syne',sans-serif; font-size:2.8rem; font-weight:800; line-height:1; }
.pf-item { font-size:.88rem; display:flex; align-items:center; gap:8px; margin:9px 0; color:var(--text); }
.btn-price { width:100%; border:none; border-radius:10px; padding:13px; font-family:'Syne',sans-serif; font-weight:700; font-size:.95rem; cursor:pointer; transition:all .2s; margin-top:20px; }

/* ── TESTIMONIALS ── */
.testi-section { padding:100px 0; background:#fff; }
.testi-card { background:var(--bg); border:1px solid var(--border); border-radius:20px; padding:30px; height:100%; }

/* ── CTA ── */
.cta-section { padding:100px 0; background:linear-gradient(135deg,var(--navy),#0D4A46); }

/* ── FOOTER ── */
.footer { background:var(--navy); padding:64px 0 28px; border-top:1px solid rgba(255,255,255,.07); }
.footer-link { display:block; color:rgba(255,255,255,.45); text-decoration:none; font-size:.88rem; margin:8px 0; transition:color .2s; }
.footer-link:hover { color:#fff; }

/* ── TOAST ── */
.toast-wrap { position:fixed; bottom:22px; right:22px; z-index:9999; display:flex; flex-direction:column; gap:10px; pointer-events:none; }
.toast-card { background:#fff; border:1px solid var(--border); border-radius:14px; padding:13px 16px; min-width:270px; max-width:330px; box-shadow:0 8px 28px rgba(0,0,0,.12); pointer-events:all; display:flex; gap:11px; align-items:flex-start; animation:slideInRight .3s ease; }
.toast-close { margin-left:auto; background:none; border:none; cursor:pointer; color:var(--muted); font-size:1rem; flex-shrink:0; }

/* Spinner */
.spinner { width:18px; height:18px; border:2.5px solid rgba(255,255,255,.3); border-top-color:#fff; border-radius:50%; animation:spin .7s linear infinite; }

/* Responsive */
@media(max-width:992px){ .hero-h1{font-size:2.3rem} }
@media(max-width:768px){
  .hamburger{display:flex!important}
  .desktop-nav{display:none!important}
  .hero-h1{font-size:2rem}
  .score-widget{max-width:100%;margin-top:36px}
  .price-card.featured{transform:none}
}
`;

/* ─────────────────────────────────────────────────────────────
   TOAST HOOK
───────────────────────────────────────────────────────────── */
function useToasts() {
  const [toasts, setToasts] = useState([]);
  const add = (icon, title, body) => {
    const id = Date.now();
    setToasts(t => [...t, { id, icon, title, body }]);
    setTimeout(() => setToasts(t => t.filter(x => x.id !== id)), 4500);
  };
  const remove = id => setToasts(t => t.filter(x => x.id !== id));
  return { toasts, add, remove };
}

/* ─────────────────────────────────────────────────────────────
   SVG SCORE RING
───────────────────────────────────────────────────────────── */
function ScoreRing({ score, color, size = 150 }) {
  const r = 60, cx = 75, cy = 75;
  const circ = 2 * Math.PI * r;
  const dash = (score / 100) * circ;
  return (
    <svg width={size} height={size} viewBox="0 0 150 150">
      <circle cx={cx} cy={cy} r={r} fill="none" stroke="rgba(255,255,255,.1)" strokeWidth="10" />
      <circle cx={cx} cy={cy} r={r} fill="none" stroke={color} strokeWidth="10"
        strokeDasharray={`${dash} ${circ}`} strokeLinecap="round"
        transform={`rotate(-90 ${cx} ${cy})`}
        style={{ transition: "stroke-dasharray 1.2s cubic-bezier(.4,0,.2,1)" }} />
    </svg>
  );
}

/* ─────────────────────────────────────────────────────────────
   DEMO LOOKUP SECTION
───────────────────────────────────────────────────────────── */
function DemoLookup({ addToast, onGoToDashboard }) {
  const [phone, setPhone] = useState("");
  const [username, setUsername] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [activeTab, setActiveTab] = useState("usage");

  const handleLookup = () => {
    const seed = (phone + username).trim();
    if (!seed) { addToast("⚠️", "Input required", "Enter a WhatsApp number or username to analyse."); return; }
    setLoading(true);
    setResult(null);
    setTimeout(() => {
      const data = generateUserData(seed);
      setResult(data);
      setLoading(false);
      addToast("✅", "Analysis complete!", `Addiction score: ${data.score}/100 — ${data.level} Risk`);
    }, 1800);
  };

  const activePlatforms = result
    ? Object.entries(result.platforms).filter(([, v]) => v)
    : [];

  return (
    <section className="demo-section" id="demo">
      <div className="container-xl">
        <div className="row gy-5 align-items-start">
          <div className="col-lg-5">
            <div className="section-eyebrow">Live Prototype</div>
            <h2 className="section-h2 mb-3">
              Check anyone's social media <span style={{ color: "var(--teal)" }}>addiction profile</span>
            </h2>
            <p className="section-sub mb-4">
              Enter a WhatsApp number or username. Our AI engine analyses usage patterns across Instagram, YouTube, Facebook, WhatsApp, Twitter/X, TikTok, Snapchat and LinkedIn — computing a real-time Addiction Score.
            </p>
            <div className="lookup-card">
              <div className="mb-3">
                <label style={{ fontSize: ".82rem", fontWeight: 600, color: "var(--teal)", display: "block", marginBottom: 6 }}>
                  📱 WhatsApp Number
                </label>
               <input
  className="lookup-input"
  placeholder="+91 98765 43210"
  style={{ color: "black" }}
  onKeyDown={e => e.key === "Enter" && handleLookup()}
/>
              </div>
              <div className="mb-3">
                <label style={{ fontSize: ".82rem", fontWeight: 600, color: "var(--teal)", display: "block", marginBottom: 6 }}>
                  👤 Social Media Username (optional)
                </label>
               <input
  className="lookup-input"
  placeholder="@username or name"
  value={username}
  style={{ color: "black" }}
  onChange={e => setUsername(e.target.value)}
  onKeyDown={e => e.key === "Enter" && handleLookup()}
/>
              </div>
              <button className={`btn-lookup w-100 ${loading ? "loading" : ""}`} onClick={handleLookup} disabled={loading}>
                {loading
                  ? <span className="d-flex align-items-center justify-content-center gap-2"><span className="spinner" />Analysing behavioural patterns…</span>
                  : "🔍 Analyse Addiction Profile"}
              </button>
              <p style={{ fontSize: ".76rem", color: "var(--muted)", marginTop: 10, textAlign: "center" }}>
                🔒 Demo uses simulated data. No real data is accessed.
              </p>
            </div>
          </div>

          {/* Results Panel */}
          <div className="col-lg-7">
            {!result && !loading && (
              <div style={{ background: "var(--bg)", border: "1px solid var(--border)", borderRadius: 20, padding: 40, textAlign: "center" }}>
                <div style={{ fontSize: "3.5rem", marginBottom: 16 }}>🧠</div>
                <div className="syne" style={{ fontSize: "1.1rem", fontWeight: 700, color: "var(--navy)", marginBottom: 8 }}>Enter details to analyse</div>
                <p style={{ color: "var(--muted)", fontSize: ".9rem" }}>The AI engine will compute an addiction score across 8 social platforms using 6 behavioural features.</p>
                <div className="d-flex flex-wrap justify-content-center gap-2 mt-4">
                  {Object.values(PLATFORMS).map(p => {
                    const Icon = p.icon;
                    return (
                      <div key={p.name} style={{ background: p.bg, borderRadius: 10, padding: "8px 14px", display: "flex", alignItems: "center", gap: 6, fontSize: ".82rem", fontWeight: 600 }}>
                        <Icon color={p.color} size={16} />{p.name}
                      </div>
                    );
                  })}
                </div>
              </div>
            )}

            {loading && (
              <div style={{ background: "var(--bg)", border: "1px solid var(--border)", borderRadius: 20, padding: 48, textAlign: "center" }}>
                <div style={{ width: 56, height: 56, border: "4px solid var(--border)", borderTopColor: "var(--teal)", borderRadius: "50%", animation: "spin .8s linear infinite", margin: "0 auto 20px" }} />
                <div className="syne" style={{ fontSize: "1rem", fontWeight: 700, color: "var(--navy)", marginBottom: 8 }}>AI Engine Running…</div>
                {["Collecting behavioural data", "Running ML inference (RF + LSTM)", "Computing addiction score", "Generating alerts & recommendations"].map((s, i) => (
                  <div key={i} style={{ fontSize: ".82rem", color: "var(--muted)", margin: "4px 0", display: "flex", alignItems: "center", justifyContent: "center", gap: 6 }}>
                    <span style={{ color: "var(--teal)" }}>✓</span>{s}
                  </div>
                ))}
              </div>
            )}

            {result && (
              <div>
                {/* Score header */}
                <div className="result-card mb-3">
                  <div className="rc-header">
                    <div>
                      <div style={{ fontSize: ".72rem", color: "rgba(255,255,255,.5)", fontWeight: 700, letterSpacing: 1, marginBottom: 4 }}>ADDICTION SCORE</div>
                      <div className="rc-score" style={{ color: result.levelColor }}>{result.score}<span style={{ fontSize: "1rem", color: "rgba(255,255,255,.5)" }}>/100</span></div>
                      <div style={{ display: "inline-block", background: `${result.levelColor}22`, border: `1px solid ${result.levelColor}`, color: result.levelColor, borderRadius: 100, padding: "3px 12px", fontSize: ".72rem", fontWeight: 700, marginTop: 6 }}>
                        {result.level} Risk
                      </div>
                    </div>
                    <div style={{ textAlign: "right" }}>
                      <div style={{ fontSize: ".72rem", color: "rgba(255,255,255,.5)", marginBottom: 4 }}>TOTAL TODAY</div>
                      <div className="mono" style={{ fontSize: "1.4rem", fontWeight: 700, color: "#fff" }}>{Math.floor(result.totalMinutes / 60)}h {result.totalMinutes % 60}m</div>
                      <div style={{ fontSize: ".7rem", color: "rgba(255,255,255,.45)" }}>across {activePlatforms.length} platforms</div>
                    </div>
                  </div>

                  {/* Tabs */}
                  <div style={{ display: "flex", borderBottom: "1px solid var(--border)" }}>
                    {[["usage", "📱 Usage"], ["alerts", "🔔 Alerts"], ["ai", "💡 AI Plan"]].map(([id, lbl]) => (
                      <button key={id} onClick={() => setActiveTab(id)} style={{ flex: 1, padding: "10px 0", border: "none", background: "none", cursor: "pointer", fontFamily: "'DM Sans',sans-serif", fontSize: ".85rem", fontWeight: activeTab === id ? 700 : 400, color: activeTab === id ? "var(--teal)" : "var(--muted)", borderBottom: activeTab === id ? "2px solid var(--teal)" : "2px solid transparent", transition: "all .2s" }}>
                        {lbl}
                      </button>
                    ))}
                  </div>

                  {/* Usage tab */}
                  {activeTab === "usage" && (
                    <div style={{ padding: "0 4px" }}>
                      {activePlatforms.map(([key, v]) => {
                        const p = PLATFORMS[key];
                        const Icon = p.icon;
                        return (
                          <div key={key} className="platform-row">
                            <div className="p-icon" style={{ background: p.bg }}><Icon color={p.color} size={17} /></div>
                            <div style={{ flex: 1, minWidth: 0 }}>
                              <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 4, fontSize: ".82rem" }}>
                                <span style={{ fontWeight: 600 }}>{p.name}</span>
                                <span style={{ color: "var(--muted)", fontSize: ".72rem" }}>limit: {p.limit}m</span>
                              </div>
                              <div className="p-bar">
                                <div className="p-bar-fill" style={{ width: `${Math.min(100, v.pct)}%`, background: v.overLimit ? "var(--red)" : v.pct > 70 ? "var(--orange)" : "var(--teal)" }} />
                              </div>
                            </div>
                            <div className={`p-time ${v.overLimit ? "over-limit" : ""}`}>{v.todayMins}m</div>
                            {v.overLimit && <span style={{ marginLeft: 6, fontSize: ".68rem", background: "rgba(239,68,68,.1)", color: "var(--red)", borderRadius: 4, padding: "1px 5px", fontWeight: 700 }}>OVER</span>}
                          </div>
                        );
                      })}
                    </div>
                  )}

                  {/* Alerts tab */}
                  {activeTab === "alerts" && (
                    <div style={{ padding: "12px 16px" }}>
                      {result.alerts.length === 0
                        ? <div style={{ textAlign: "center", color: "var(--muted)", padding: "24px 0" }}>✅ No alerts — usage looks healthy!</div>
                        : result.alerts.map((a, i) => (
                          <div key={i} className="alert-item">
                            <div className="alert-icon-box" style={{ background: `${a.color}15` }}>
                              <span style={{ fontSize: "1.1rem" }}>{a.icon}</span>
                            </div>
                            <div>
                              <div style={{ fontWeight: 700, fontSize: ".88rem", marginBottom: 2 }}>{a.title}</div>
                              <div style={{ fontSize: ".78rem", color: "var(--muted)", lineHeight: 1.5 }}>{a.desc}</div>
                              <div style={{ fontSize: ".68rem", color: "var(--muted)", marginTop: 3 }}>🕐 {a.time}</div>
                            </div>
                          </div>
                        ))
                      }
                    </div>
                  )}

                  {/* AI tab */}
                  {activeTab === "ai" && (
                    <div style={{ padding: "12px 16px" }}>
                      {result.recommendations.map((r, i) => (
                        <div key={i} style={{ display: "flex", alignItems: "center", gap: 12, padding: "12px 0", borderBottom: "1px solid var(--bg)" }}>
                          <div style={{ width: 36, height: 36, borderRadius: 9, background: `${r.color}15`, display: "flex", alignItems: "center", justifyContent: "center", fontSize: "1.1rem", flexShrink: 0 }}>{r.icon}</div>
                          <div style={{ flex: 1, minWidth: 0 }}>
                            <div style={{ fontWeight: 700, fontSize: ".88rem", marginBottom: 2 }}>{r.title}</div>
                            <div style={{ fontSize: ".78rem", color: "var(--muted)", lineHeight: 1.5 }}>{r.desc}</div>
                          </div>
                          <button onClick={() => addToast("✅", r.action + " applied!", r.title + " has been activated.")}
                            style={{ background: "var(--teal)", color: "#fff", border: "none", borderRadius: 7, padding: "6px 12px", fontSize: ".76rem", fontWeight: 600, cursor: "pointer", whiteSpace: "nowrap" }}>
                            {r.action}
                          </button>
                        </div>
                      ))}
                    </div>
                  )}

                  {/* Weekly trend mini */}
                  <div style={{ padding: "14px 16px", borderTop: "1px solid var(--border)" }}>
                    <div style={{ fontSize: ".72rem", fontWeight: 700, color: "var(--muted)", marginBottom: 8, letterSpacing: .5 }}>7-DAY SCORE TREND</div>
                    <div style={{ display: "flex", alignItems: "flex-end", gap: 6, height: 52 }}>
                      {result.weekTrend.map((d, i) => {
                        const h = Math.max(8, Math.round((d.score / 100) * 52));
                        const c = d.score > 60 ? "var(--red)" : d.score > 30 ? "var(--orange)" : "var(--teal)";
                        return (
                          <div key={i} style={{ flex: 1, display: "flex", flexDirection: "column", alignItems: "center", gap: 3 }}>
                            <div style={{ width: "100%", height: h, background: c, borderRadius: "3px 3px 0 0" }} title={`${d.day}: ${d.score}`} />
                            <span style={{ fontSize: ".58rem", color: "var(--muted)", fontWeight: 600 }}>{d.day[0]}</span>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                </div>

                <button className="btn-primary w-100" onClick={() => onGoToDashboard(result)}>
                  <FiBarChart2 /> View Full Dashboard
                </button>
              </div>
            )}
          </div>
        </div>
      </div>
    </section>
  );
}

/* ─────────────────────────────────────────────────────────────
   FEATURES SECTION
───────────────────────────────────────────────────────────── */
function FeaturesSection() {
  const feats = [
    { icon: RiBrainLine, color: "var(--red)", bg: "rgba(239,68,68,.08)", title: "AI Behavioural Analysis", desc: "LSTM + Random Forest ensemble learns your unique usage patterns in 3 days. Detects binge sessions, late-night usage, and compulsive frequency with 94.2% accuracy." },
    { icon: MdOutlineSpeed, color: "var(--orange)", bg: "rgba(249,115,22,.08)", title: "Real-time Addiction Score", desc: "0–100 score updated every 15 minutes using 6 weighted behavioural features: screen time, late-night usage, session frequency, scroll depth, interaction ratio, and mood." },
    { icon: RiNotification3Line, color: "var(--teal)", bg: "rgba(13,148,136,.08)", title: "Smart Alert Engine", desc: "6 alert types: usage limit breach, late-night detection, score spike, break reminder, weekly report, and goal achievement. Delivered via push, email, and SMS." },
    { icon: MdOutlineAnalytics, color: "var(--green)", bg: "rgba(16,185,129,.08)", title: "Interactive Dashboard", desc: "Live charts, 28-cell heatmap, per-app breakdowns, platform comparison, and trend analysis. Export weekly/monthly reports as PDF or CSV." },
    { icon: RiLightbulbFill || FiZap, color: "#6D2E46", bg: "rgba(109,46,70,.08)", title: "AI Recommendation Engine", desc: "Personalised action plans: set app limits, optimal usage windows, mindfulness reminders, and digital detox challenges — all backed by behavioural science." },
    { icon: RiShieldCheckLine, color: "var(--navy)", bg: "rgba(11,31,75,.06)", title: "Privacy-First Architecture", desc: "Data processed locally first. Cloud sync AES-256 encrypted. GDPR compliant. Users can export or delete all data anytime. Zero data selling." },
  ];
  return (
    <section className="features-section" id="features">
      <div className="container-xl">
        <div className="text-center mb-5">
          <div className="section-eyebrow">Core Features</div>
          <h2 className="section-h2 mb-3">Everything you need to <span style={{ color: "var(--teal)" }}>break the cycle</span></h2>
          <p className="section-sub mx-auto">A complete AI-driven digital wellness system with real algorithms, not just dashboards.</p>
        </div>
        <div className="row gy-4">
          {feats.map((f, i) => {
            const Icon = f.icon;
            return (
              <div key={i} className="col-md-6 col-xl-4">
                <div className="feat-card">
                  <div className="feat-icon" style={{ background: f.bg }}><Icon size={24} color={f.color} /></div>
                  <div className="syne" style={{ fontWeight: 700, fontSize: "1.05rem", marginBottom: 10 }}>{f.title}</div>
                  <div style={{ color: "var(--muted)", fontSize: ".9rem", lineHeight: 1.65 }}>{f.desc}</div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}

/* ─────────────────────────────────────────────────────────────
   HOW IT WORKS
───────────────────────────────────────────────────────────── */
function HowItWorks() {
  const steps = [
    { n: "01", icon: FiUsers, t: "Sign Up", d: "Register with email or Google OAuth. No credit card required." },
    { n: "02", icon: FiSmartphone, t: "Connect Apps", d: "Enter your WhatsApp number or username to start monitoring." },
    { n: "03", icon: RiBrainLine, t: "AI Calibrates", d: "3-day baseline period. ML models personalise your thresholds." },
    { n: "04", icon: FiActivity, t: "Live Scoring", d: "Addiction score updated every 15 min. Alerts triggered instantly." },
  ];
  return (
    <section className="how-section" id="how">
      <div className="container-xl">
        <div className="text-center mb-5">
          <div className="section-eyebrow">How It Works</div>
          <h2 className="section-h2">Running in <span style={{ color: "var(--orange)" }}>3 minutes</span></h2>
        </div>
        <div className="row gy-4 text-center">
          {steps.map((s, i) => {
            const Icon = s.icon;
            return (
              <div key={i} className="col-6 col-md-3">
                <div className="step-num mx-auto"><Icon size={22} /></div>
                <div className="syne" style={{ fontWeight: 700, fontSize: "1rem", marginBottom: 8 }}>{s.t}</div>
                <div style={{ color: "var(--muted)", fontSize: ".88rem", lineHeight: 1.65 }}>{s.d}</div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}


/* ─────────────────────────────────────────────────────────────
   TESTIMONIALS
───────────────────────────────────────────────────────────── */
function TestimonialsSection() {
  const testis = [
    { init: "P", color: "var(--teal)", name: "Priya Sharma", role: "Software Engineer, Bangalore", stars: 5, text: "I had no idea I was spending 8 hours on Instagram daily. AddictAI's score alert shocked me into changing. Down to 2 hours in 3 weeks." },
    { init: "R", color: "var(--orange)", name: "Rahul Mehra", role: "MBA Student, Delhi", stars: 5, text: "The late-night alert literally changed my sleep. I was scrolling until 2AM every night. Now apps lock at 10PM automatically." },
    { init: "D", color: "#6D2E46", name: "Dr. Deepa Rao", role: "Clinical Psychologist, Mumbai", stars: 4, text: "As a psychologist, I recommend AddictAI to my patients. The weekly PDF reports are excellent for therapy sessions." },
  ];
  return (
    <section className="testi-section" id="testimonials">
      <div className="container-xl">
        <div className="text-center mb-5">
          <div className="section-eyebrow">Testimonials</div>
          <h2 className="section-h2">Real users, real <span style={{ color: "var(--teal)" }}>results</span></h2>
        </div>
        <div className="row gy-4">
          {testis.map((t, i) => (
            <div key={i} className="col-md-4">
              <div className="testi-card">
                <div style={{ color: "var(--orange)", fontSize: "1rem", marginBottom: 10 }}>{"★".repeat(t.stars)}{"☆".repeat(5 - t.stars)}</div>
                <p style={{ fontSize: ".94rem", lineHeight: 1.75, fontStyle: "italic", marginBottom: 20, color: "var(--text)" }}>"{t.text}"</p>
                <div className="d-flex align-items-center">
                  <div style={{ width: 42, height: 42, borderRadius: "50%", background: t.color, display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 700, color: "#fff", fontSize: ".95rem", marginRight: 12, flexShrink: 0 }}>{t.init}</div>
                  <div>
                    <div style={{ fontWeight: 600, fontSize: ".88rem" }}>{t.name}</div>
                    <div style={{ color: "var(--muted)", fontSize: ".78rem" }}>{t.role}</div>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ─────────────────────────────────────────────────────────────
   TOAST CONTAINER
───────────────────────────────────────────────────────────── */
function ToastContainer({ toasts, remove }) {
  return (
    <div className="toast-wrap">
      {toasts.map(t => (
        <div key={t.id} className="toast-card">
          <span style={{ fontSize: "1.25rem", flexShrink: 0, marginTop: 2 }}>{t.icon}</span>
          <div style={{ flex: 1, minWidth: 0 }}>
            <div style={{ fontWeight: 700, fontSize: ".86rem", marginBottom: 2 }}>{t.title}</div>
            <div style={{ fontSize: ".76rem", color: "var(--muted)" }}>{t.body}</div>
          </div>
          <button className="toast-close" onClick={() => remove(t.id)}>✕</button>
        </div>
      ))}
    </div>
  );
}

/* ─────────────────────────────────────────────────────────────
   LANDING PAGE ROOT
───────────────────────────────────────────────────────────── */
export default function LandingPage() {
  const { toasts, add: addToast, remove } = useToasts();
  const [mobileOpen, setMobileOpen] = useState(false);

  const scrollTo = id => {
    document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });
    setMobileOpen(false);
  };

   const router = useRouter();

  const onGoToDashboard = () => {
    router.push("/dashboard");
  };


  // Demo widget score for hero
  const demoData = generateUserData("demo-user-seed");

  return (
    <>
      <style>{STYLES}</style>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" />

      {/* NAV */}
      <nav className="lp-nav py-2">
        <div className="container-xl">
          <div className="d-flex align-items-center justify-content-between gap-3">
            <span className="lp-brand">⚡ Addict<span>AI</span></span>
            <div className="desktop-nav d-flex align-items-center gap-4">
              {["Features", "Demo", "How It Works", "Pricing", "Testimonials"].map(l => (
                <span key={l} className="lp-navlink" onClick={() => scrollTo(l.toLowerCase().replace(/ /g, ""))}>{l}</span>
              ))}
            </div>
            <div className="d-flex align-items-center gap-3">
              <button className="hamburger" onClick={() => setMobileOpen(o => !o)}>
                {mobileOpen ? <FiX size={22} /> : <FiMenu size={22} />}
              </button>
   <button className="btn-nav" onClick={onGoToDashboard}>
      Try Dashboard →
    </button>            </div>
          </div>
          {mobileOpen && (
            <div style={{ paddingBottom: 12, borderTop: "1px solid rgba(255,255,255,.1)", marginTop: 8 }}>
              {["Features", "Demo", "How It Works", "Pricing", "Testimonials"].map(l => (
                <div key={l} className="lp-navlink d-block py-2" onClick={() => scrollTo(l.toLowerCase().replace(/ /g, ""))}>{l}</div>
              ))}
            </div>
          )}
        </div>
      </nav>

      {/* HERO */}
      <section className="hero" id="home">
        <div className="container-xl">
          <div className="row align-items-center gy-5 py-5">
            <div className="col-lg-6">
              <div className="hero-badge fade-up"><span className="pulse-dot" /><RiBrainLine size={14} style={{ marginRight: 4 }} />AI-Powered Mental Health Tech</div>
              <h1 className="hero-h1 fade-up delay-1">
                Detect Social Media <span className="acc">Addiction</span> Before It Controls You
              </h1>
              <p className="hero-sub mt-3 mb-4 fade-up delay-2">
                AddictAI uses machine learning to analyse usage patterns across Instagram, YouTube, WhatsApp, Facebook, TikTok and more — computing a real-time Addiction Score and sending smart interventions.
              </p>
              <div className="d-flex flex-wrap gap-3 fade-up delay-3">
                <button className="btn-primary" onClick={() => scrollTo("demo")}>
                  <FiZap /> Analyse Now — Free
                </button>
                <button className="btn-outline" onClick={() => scrollTo("features")}>
                  See Features <FiChevronRight />
                </button>
              </div>
              <div className="d-flex flex-wrap gap-3 mt-4 fade-up delay-4">
                <span style={{ color: "rgba(255,255,255,.6)", fontSize: ".82rem", display: "flex", alignItems: "center", gap: 5 }}><span className="pulse-dot" />Live monitoring</span>
                <span style={{ color: "rgba(255,255,255,.6)", fontSize: ".82rem" }}>✓ Free tier forever</span>
                <span style={{ color: "rgba(255,255,255,.6)", fontSize: ".82rem" }}>✓ 94.2% ML accuracy</span>
              </div>
            </div>
            <div className="col-lg-6 d-flex justify-content-center justify-content-lg-end fade-up delay-2">
              <div className="score-widget float">
                <div className="syne" style={{ fontWeight: 700, color: "#fff", textAlign: "center", marginBottom: 16, fontSize: ".9rem" }}>📊 Live Addiction Score</div>
                <div className="score-ring-wrap">
                  <ScoreRing score={demoData.score} color={demoData.levelColor} />
                  <div className="score-ring-center">
                    <div className="score-val" style={{ color: demoData.levelColor }}>{demoData.score}</div>
                    <div style={{ fontSize: ".6rem", color: "rgba(255,255,255,.5)", letterSpacing: 1 }}>/ 100</div>
                  </div>
                </div>
                <div style={{ textAlign: "center", marginBottom: 16 }}>
                  <span style={{ background: `${demoData.levelColor}22`, border: `1px solid ${demoData.levelColor}`, color: demoData.levelColor, borderRadius: 100, padding: "4px 14px", fontSize: ".72rem", fontWeight: 700 }}>
                    ⚠️ {demoData.level.toUpperCase()} RISK
                  </span>
                </div>
                {[
                  { name: "Screen Time", val: `${Math.floor(demoData.totalMinutes / 60)}h ${demoData.totalMinutes % 60}m`, pct: Math.min(100, Math.round(demoData.totalMinutes / 4.8)), color: demoData.levelColor },
                  { name: "Sessions", val: `${demoData.activeList.reduce((s, [, v]) => s + v.opens, 0)}x`, pct: 65, color: "var(--orange)" },
                  { name: "Platforms", val: `${demoData.activeList.length} apps`, pct: demoData.activeList.length * 12, color: "var(--teal2)" },
                  { name: "Late Night", val: demoData.activeList.some(([, v]) => v.lateNight) ? "Yes" : "No", pct: 40, color: "#F97316" },
                ].map((b, i) => (
                  <div key={i} className="sbar-row">
                    <span className="sbar-name">{b.name}</span>
                    <div className="sbar-track"><div className="sbar-fill" style={{ width: `${b.pct}%`, background: b.color }} /></div>
                    <span className="sbar-val">{b.val}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* TRUST STRIP */}
      <section className="trust-strip">
        <div className="container-xl">
          <div className="row gy-4 text-center">
            {[["4.8B", "Social Media Users Worldwide"], ["6.4h", "Avg Daily Screen Time"], ["40%", "Show Addictive Behaviour"], ["94.2%", "ML Detection Accuracy"]].map(([n, l], i) => (
              <div key={i} className="col-6 col-md-3">
                <div className="trust-num">{n}</div>
                <div className="trust-lbl">{l}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* DEMO LOOKUP */}
      <DemoLookup addToast={addToast} onGoToDashboard={onGoToDashboard} />

      {/* FEATURES */}
      <FeaturesSection />

      {/* HOW IT WORKS */}
      <HowItWorks />

    

      {/* TESTIMONIALS */}
      <TestimonialsSection />

      {/* CTA */}
      <section className="cta-section text-center" id="contact">
        <div className="container-xl">
          <div className="section-eyebrow" style={{ color: "var(--teal2)" }}>Get Started Today</div>
          <h2 className="section-h2 mt-2 mb-3" style={{ color: "#fff", maxWidth: 600, margin: "12px auto 20px" }}>
            "Detect. Alert. <span style={{ color: "var(--orange)" }}>Heal.</span>"
          </h2>
          <p style={{ color: "rgba(255,255,255,.62)", maxWidth: 460, margin: "0 auto 36px", fontSize: ".98rem", lineHeight: 1.75 }}>
            Join 50,000+ users who've taken control of their digital lives with AddictAI.
          </p>
          <button className="btn-primary" style={{ fontSize: "1.05rem", padding: "15px 40px" }} onClick={() => onGoToDashboard(demoData)}>
            <FiZap /> Launch Dashboard
          </button>
          <p style={{ color: "rgba(255,255,255,.35)", fontSize: ".8rem", marginTop: 18 }}>Free tier · No credit card · GDPR compliant</p>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="footer">
        <div className="container-xl">
          <div className="row gy-4">
            <div className="col-lg-4">
              <span className="lp-brand">⚡ Addict<span>AI</span></span>
              <p style={{ color: "rgba(255,255,255,.45)", fontSize: ".86rem", lineHeight: 1.7, maxWidth: 280, marginTop: 12 }}>
                AI-powered social media addiction detection, alerting & notification system. PDA College of Engineering, Dept. of CSE, Kalaburagi.
              </p>
            </div>
            {[
              { head: "Product", links: ["Features", "Demo", "How It Works", "Pricing"] },
              { head: "Tech Stack", links: ["Next.js + React", "Python FastAPI", "MongoDB Atlas", "scikit-learn / TF"] },
              { head: "Legal", links: ["Privacy Policy", "Terms of Use", "GDPR", "Contact"] },
            ].map((c, i) => (
              <div key={i} className="col-6 col-lg-2">
                <div style={{ fontFamily: "'Syne',sans-serif", fontWeight: 700, fontSize: ".82rem", color: "#fff", letterSpacing: 1, textTransform: "uppercase", marginBottom: 14 }}>{c.head}</div>
                {c.links.map((l, j) => <a key={j} href="#" className="footer-link">{l}</a>)}
              </div>
            ))}
          </div>
          <hr style={{ borderColor: "rgba(255,255,255,.07)", margin: "40px 0 20px" }} />
          <div className="d-flex flex-wrap justify-content-between gap-3">
            <span style={{ color: "rgba(255,255,255,.32)", fontSize: ".8rem" }}>© 2026 AddictAI · PDA College of Engineering · Team: Dattu, Abhishek, Vikas Havanoor · Guide: Dr. Anuradha Moti</span>
            <span style={{ color: "rgba(255,255,255,.32)", fontSize: ".8rem" }}>Made with ❤️ for Mental Health</span>
          </div>
        </div>
      </footer>

      <ToastContainer toasts={toasts} remove={remove} />
    </>
  );
}

// Re-export helpers for Dashboard
export { generateUserData, PLATFORMS, WEIGHTS, generateAlerts, generateRecommendations };